version: '3.3'

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/data/postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      
  server:
    build: .
    ports:
      - 5000:5000
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_USER: ${DB_USER}

volumes:
  postgres_data:    
  