version: '3.3'

services:
  db:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      
  server:
    build: .
    ports:
      - 5000:5000
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_USER: ${DB_USER}
    
  