version: '3.9'

services:
  db:
    image: 'postgres:15'
    ports:
      - '5555:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: postgres
  
  server:
    build: .
    ports:
      - '5000:5000'

networks:
  default:
    external:
      name: test

  